# Generated by Django 5.2 on 2026-09-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='query',
            name='organisation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
