# Generated by Django 5.2 on 2026-09-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_query_contact_email_query_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='reject_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
