# Generated by Django 5.2 on 2026-09-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_draft_reject_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedresponse',
            name='kind',
            field=models.CharField(choices=[('media_response', 'Media response'), ('press_release', 'Press release'), ('statement', 'Official statement'), ('faq', 'FAQ'), ('other', 'Other messaging')], default='media_response', max_length=24),
        ),
        migrations.AddField(
            model_name='approvedresponse',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='approvedresponse',
            name='question',
            field=models.TextField(blank=True, default=''),
        ),
    ]
