# Generated by Django 5.2 on 2026-09-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_approvedresponse_kind_approvedresponse_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='media_kind',
            field=models.CharField(blank=True, default='media_response', max_length=24),
        ),
    ]
